// <auto-generated />
using System;
using MSSemantic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MSSemantic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MSSemantic.Models.MessageModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_messages_session_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("MSSemantic.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail")
                        .HasJsonPropertyName("detail");

                    b.Property<int?>("InStock")
                        .HasColumnType("integer")
                        .HasColumnName("in_stock")
                        .HasJsonPropertyName("inStock");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price")
                        .HasJsonPropertyName("price");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Masaüstünüzde şık ve modern bir aydınlatma çözümü",
                            Detail = "Masa lambası, çalışma alanınızı aydınlatmak için tasarlanmış şık ve modern bir aydınlatma çözümüdür. Ayarlanabilir ışık seviyesi ve enerji tasarruflu LED teknolojisi ile kullanıcı dostu bir deneyim sunar. 220V güç kaynağı ile çalışır. 2 yıl garanti ile gelir. 25x30x80 cm ebatlarındadır.",
                            InStock = 21,
                            Name = "Masa Lambası",
                            Price = 300m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dış mekan veranda ışığı",
                            Detail = "Tavan aydınlatması, dış mekan veranda ışığı olarak tasarlanmıştır. Suya dayanıklı malzemelerden üretilmiştir ve enerji tasarruflu LED teknolojisi ile donatılmıştır. 220V güç kaynağı ile çalışır. 2 yıl garanti ile gelir. 50x50x20 cm ebatlarındadır.",
                            InStock = 0,
                            Name = "Tavan Aydınlatması",
                            Price = 500m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Şık ve modern bir avize",
                            Detail = "Avize, şık ve modern bir tasarıma sahip olup, yaşam alanınıza estetik bir dokunuş katar. Enerji tasarruflu LED teknolojisi ile donatılmıştır. 220V güç kaynağı ile çalışır. 2 yıl garanti ile gelir. 60x60x40 cm ebatlarındadır.",
                            InStock = 35,
                            Name = "Avize",
                            Price = 800m
                        });
                });

            modelBuilder.Entity("MSSemantic.Models.SessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("MSSemantic.Models.MessageModel", b =>
                {
                    b.HasOne("MSSemantic.Models.SessionModel", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MSSemantic.Models.SessionModel", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
